import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import {VscGithub} from "react-icons/vsc"
// import {TbBrandLinkedin} from "react-icons/tb"
import {RiMediumLine, RiLinkedinBoxLine, RiGithubLine} from "react-icons/ri"
import {BsMoonStarsFill} from "react-icons/bs"
import { useState } from 'react'
// import { Link } from 'react-router-dom'

export default function Home() {
  const[darkMode, setDarkMode] = useState(false);
  // const [isScrolled, setIsScrolled] = useState(false);

  return (
    <div className={`${darkMode ? "dark" : ""}`}>
    <Head>
        <title>This is Annisa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link type="image/png" sizes="96x96" rel="icon" href="../public/love-pink.png" />
      </Head>

      <main>

        <section className='bg-fuchsia-50 font-semibold text-slate-600 dark:bg-slate-800'>

          {/* Navigation Bar Section */}
          <nav className={`bg-inherit p-2 mt-0 fixed w-full z-10 top-0 dark:text-rose-100`}>
              <ul className='container mx-auto flex flex-wrap py-5 justify-center gap-24'>
                <li>
                  <a className='cursor-pointer hover:text-rose-400 hover:font-semibold'>About Me</a>
                </li>
                <li>
                  <a className='cursor-pointer hover:text-rose-400 hover:font-semibold'>Learning Journey</a>
                </li>
                {/* <li>
                  <a href=''>Education</a>
                </li> */}
                <li>
                  <a className='cursor-pointer hover:text-rose-400 hover:font-semibold'>Contact</a>
                </li>
                <li>
                  <div className='px-4 py-2 border-none rounded-xl text-pink-50 bg-yellow-400 dark:bg-sky-800 hover:text-sky-800 dark:hover:text-yellow-400 dark:text-yellow-50 cursor-pointer'
                  onClick={() => setDarkMode(!darkMode)}>
                    <BsMoonStarsFill />
                  </div>
                </li>
              </ul>
          </nav>

          <div className="pt-28 pb-24 min-h-screen relative">
          {/* Greetings Section */}
            <div className='mb-5'>
              <img id="fotoAku" className='shadow-custom vert-move rounded-full' src="https://firebasestorage.googleapis.com/v0/b/xxxxx-5413a.appspot.com/o/foto-square.jpg?alt=media&token=d6998b27-2188-4b05-b102-b14de6bc4c22"></img>
            </div>
            <div className='px-60 text-center py-2'>
              <h1 className='mb-5 text-rose-400'> 
                <b>
                  Annisa Novaguinea
                </b> 
              </h1>
              <p className='self-desc dark:text-rose-100'>
                A fresh graduate information system student from UPN Veteran Jakarta. Passionate about creating best experience product for everyone!✨
              </p>
            </div>
            {/* Social Media Section */}
            <div className='mt-10'>
              <div className="text-center text-5xl flex justify-center gap-36 dark:text-rose-50">
                <Link className='text-center text-5xl' target={'_blank'} href={'https://www.linkedin.com/in/novaguinea/'}>
                  <RiLinkedinBoxLine className='cursor-pointer hover:text-rose-400' />
                </Link>
                <Link className='text-center text-5xl' target={'_blank'} href={'https://medium.com/@novaguinea'}>
                  <RiMediumLine className='cursor-pointer hover:text-rose-400' />
                </Link>
                <Link className='text-center text-5xl' target={'_blank'} href={'https://github.com/novaguinea'}>
                  <VscGithub className='cursor-p ointer hover:text-rose-400'/>
                </Link>
              </div>
            </div>
          </div >

          <hr className='dark:bg-slate-800 justify-center'></hr>
          
          <div className='text-left px-36 py-24 pb-56 gap-12 grid grid-cols-2'>

            <div className='text-right mr-6'>
              <h2>
                Learning Journey
              </h2>
              <p className='dark:text-rose-50'>
                Here are my potions after a lot of experiments!🧪
              </p>
            </div>


            <div className='grid grid-cols-2 text-center text-gray-800 dark:text-rose-50 gap-4'>
              <div className='cursor-pointer porto-card bg-rose-200 hover:bg-rose-400 hover:text-rose-50 dark:bg-slate-600 hover:dark:bg-rose-200 dark:hover:text-rose-500 p-10'>
                <a href='twitter.com'>Product Management</a>
              </div>
              <div className='cursor-pointer porto-card bg-rose-200 hover:bg-rose-400 hover:text-rose-50 dark:bg-slate-600 hover:dark:bg-rose-200 dark:hover:text-rose-500 p-10'>
                <a>Business Intelligence</a> 
              </div>
              <div className='cursor-pointer porto-card bg-rose-200 hover:bg-rose-400 hover:text-rose-50 dark:bg-slate-600 hover:dark:bg-rose-200 dark:hover:text-rose-500 p-10'>
                <a>UI/UX Design</a> 
              </div>
              <div className='cursor-pointer porto-card bg-rose-200 hover:bg-rose-400 hover:text-rose-50 dark:bg-slate-600 hover:dark:bg-rose-200 dark:hover:text-rose-500 p-10'>
                <a>Web Development</a>
              </div>
            </div>
              
          </div>
        </section>

      </main>
    </div>
  )
}
